spring.application.name=web-gui

# This app will run on the main port 8080
server.port=8080

# --- API Locations ---
# Tell our GUI app where to find the other services
api.users.url=http://localhost:8081
api.products.url=http://localhost:8082
api.sales.url=http://localhost:8083