spring.application.name=users-api
# --- PostgreSQL User Database ---
spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=user_admin
spring.datasource.password=password

# --- JPA Settings ---
# Automatically create/update tables
spring.jpa.hibernate.ddl-auto=update
# Optional: Specify the dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Server Port ---
# We'll run this service on port 8081 (so it doesn't conflict with the others)
server.port=8081