spring.application.name=products-api

# --- Oracle Product Database ---
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=product_admin
spring.datasource.password=password

# --- JPA Settings ---
spring.jpa.hibernate.ddl-auto=update
# Oracle dialect is important for the sequence generation
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# --- Server Port ---
# Run this service on port 8082
server.port=8082